version: '3'

services:

  composer:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: ${APP_NAME}_composer
    volumes:
      - ./:/var/www/
    working_dir: /var/www/
    entrypoint: [ 'composer' ]
    # docker-compose run --rm composer ______

  npm:
    build:
      context: .
      dockerfile: docker/npm/Dockerfile
      args:
        - PHP_IMAGE_NAME=${APP_NAME}_composer
    container_name: imet_core_npm
    volumes:
      - ./:/var/www/
    working_dir: /var/www/
    entrypoint: [ 'npm' ]
    # docker-compose run --rm npm ______
