BEGIN;

-- Remove unused columns
ALTER TABLE persons DROP COLUMN IF EXISTS category_filter;
ALTER TABLE persons DROP COLUMN IF EXISTS address;
ALTER TABLE persons DROP COLUMN IF EXISTS city;
ALTER TABLE persons DROP COLUMN IF EXISTS telephone;
ALTER TABLE persons DROP COLUMN IF EXISTS reference;
ALTER TABLE persons DROP COLUMN IF EXISTS document;
ALTER TABLE persons DROP COLUMN IF EXISTS role_ofac;
ALTER TABLE persons DROP COLUMN IF EXISTS role_redd;
ALTER TABLE users DROP COLUMN IF EXISTS profile_type;

COMMIT;
